Issue #3370: lib-device-measurement pushed
ekanek/android-device-measurement-lib pull request #1
Opened 2020-08-20 06:32 UTC by pkpardeep482

2020-08-21 22:29 UTC, chandranshu12 requested changes

2020-08-21 22:29 UTC, chandranshu12 commented on lib-device-measurement-utils/build.gradle
> +        minSdkVersion 23
Set this to 16. We need to support that and I don't want to start with something so high and then never be able to go down to lower versions.

2020-08-21 22:29 UTC, chandranshu12 commented on lib-device-measurement-utils/src/main/java/in/foxy/lib_device_measurement_utils/DeviceInfo.java
> +        if(actManager!=null){
spaces before and after the comparison sign.

2020-08-21 22:29 UTC, chandranshu12 commented on lib-device-measurement-utils/src/test/java/in/foxy/lib_device_measurement_utils/ExampleUnitTest.java
> +}
If you want to write a unit test cases, write a proper one. Please don't include autogenerated files.

2020-08-21 22:29 UTC, chandranshu12 commented on lib-device-measurement-utils/src/main/java/in/foxy/lib_device_measurement_utils/DeviceInfo.java
> +        return bytesAvailable / (1024 * 1024);
Lots of duplication again with the previous method.

2020-08-21 22:29 UTC, chandranshu12 commented on lib-device-measurement-utils/src/main/java/in/foxy/lib_device_measurement_utils/DeviceInfo.java
> +    }
1. Lots of code duplication with the previous method. Would probably help if there was a common helper function.
2. Also, I don't see why you should not fetch both available and total memory in one go and return a hash or update a hash. Alternatively, you can cache the totalRam and totalStorage values in class variables once when they are calculated at the start and never fetch them again.

2020-08-21 22:29 UTC, chandranshu12 commented on lib-device-measurement-utils/src/main/java/in/foxy/lib_device_measurement_utils/DeviceInfo.java
> +        return ""+width+"x"+height;
1. This should be cached at the application startup in a class variable and never calculated again.
2. Along with height and width in pixels, you should also fetch the pixel density. Otherwise, this data will barely make any sense.

2020-08-21 22:29 UTC, chandranshu12 commented on lib-device-measurement-utils/src/androidTest/java/in/foxy/lib_device_measurement_utils/ExampleInstrumentedTest.java
> +package in.foxy.lib_device_measurement_utils;
If you want to write a unit test cases, write a proper one. Please don't include autogenerated files.

2020-08-21 22:29 UTC, chandranshu12 commented on lib-device-measurement-utils/build.gradle
> +            minifyEnabled false
Enable this and test your build with this enabled.

2020-08-22 00:01 UTC, chandranshu12 requested changes
Why are there no measurements for Camera? I know we'll need permission but once the permission has been taken, we should start reporting camera stats from that point onwards.

2020-08-22 08:01 UTC, pkpardeep482 commented on lib-device-measurement-utils/build.gradle
> +        minSdkVersion 23
Done

2020-08-22 08:05 UTC, pkpardeep482 commented on lib-device-measurement-utils/src/main/java/in/foxy/lib_device_measurement_utils/DeviceInfo.java
> +        if(actManager!=null){
resolved

2020-08-22 08:07 UTC, pkpardeep482 commented on lib-device-measurement-utils/src/androidTest/java/in/foxy/lib_device_measurement_utils/ExampleInstrumentedTest.java
> +package in.foxy.lib_device_measurement_utils;
removed autogenerated file

2020-08-25 12:52 UTC, chandranshu12 approved these changes

2020-08-25 12:53 UTC, merged